CREATE TABLE IF NOT EXISTS `#__articlepush_sites` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `site_name` VARCHAR(255) NOT NULL,
  `api_url` VARCHAR(500) NOT NULL,
  `api_username` VARCHAR(255) NOT NULL,
  `api_password` VARCHAR(255) NOT NULL,
  `created` DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
